### ISSUE TITLE
ERRORS in upload-last

### ISSUE THREAD

**Issue by AtMostafa** [BeNeuroLab/beneuro_experimental_data_organization#41]
bnd still generates multiple pages of errors in the behavioural PC, I think indicating that video and ephys don't exist

**Comment by bagibence** [comment]
What if you add `--ignore-ephys --ignore-videos`?

**Comment by AtMostafa** [comment]
we really don't want to type more than essential... can you change the default to upload whatever and write 1 line of warning that ephys+video is not found? now it prints 2-3 pages that makes is difficult to understand if the available data got uploaded or not

**Comment by AtMostafa** [comment]
here's the errors:
![image](https://github.com/BeNeuroLab/beneuro_experimental_data_organization/assets/9393635/0aca3f33-f892-4c3b-9ae9-8aa7cdd8264e)

**Comment by bagibence** [comment]
I think it's better to throw errors that tell you that something is wrong instead of failing quietly.
People usually either don't notice warnings or they just ignore them, so I'm pretty sure we'll end up with stuff not uploading without us noticing.

I thought it was nice that there is a traceback helping you debug, but I could see if I can remove it and only display the error message on the bottom.

Another solution to not typing that much could be that if you don't specify the `--ignore-ephys` and co., then it will ask you yes/no, so you only have to type "y" or "n" 3 times.

Would these help?

**Comment by AtMostafa** [comment]
maybe unhide the error with a `--verbose` flag or something? 
yes/no would be better, but still there will never be a case where all the data streams are on the same machine, so it's a lot of yes/no questions that are not essential. I still think printing 3 lines is better, no matter the case:
```
behaviour: uploaded/not
ephys: uploaded/not
cameras: uploaded/no
```
Then if it is not as the user expects, they can investigate
If yes/no questions are easier to implement, that's a good enough solution.

**Comment by bagibence** [comment]
Okay, let's agree on the yes/no solution for now, and see how it works out.

**Comment by bagibence** [comment]
@AtMostafa Let me know how it is now, and I'll close this if it's working okay.

**Comment by AtMostafa** [comment]
I will check it out later today!

**Comment by bagibence** [comment]
@AtMostafa How has it been working out? Can we settle on this?

**Comment by AtMostafa** [comment]
working well!
